# ---------- test-arm64.yaml ----------
apiVersion: v1
kind: Pod
metadata:
  name: arm64-pod
spec:
  containers:
  - name: nginx
    image: nginx # Must support arm64
  nodeSelector:
    kubernetes.io/arch: arm64


---

# ---------- test-x86.yaml ----------
apiVersion: v1
kind: Pod
metadata:
  name: x86-pod
spec:
  containers:
  - name: nginx
    image: nginx # Must support amd64
  nodeSelector:
    kubernetes.io/arch: amd64
