# ---------- test-arm64.yaml ----------
apiVersion: v1
kind: Pod
metadata:
  name: hello-arm
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
  containers:
  - name: pause
    image: public.ecr.aws/eks-distro/kubernetes/pause:3.9

---

# ---------- test-x86.yaml ----------
apiVersion: v1
kind: Pod
metadata:
  name: hello-x86
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
  - name: pause
    image: public.ecr.aws/eks-distro/kubernetes/pause:3.9

