# ------------------------------
# ARM64 Spot NodePool
# ------------------------------
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: arm64-spot
spec:
  weight: 10
  limits:
    cpu: "256"                         # soft quota
  template:
    spec:
      nodeClassRef:
        name: ec2-nodeclass-default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: "24h"
    # expireAfter can be added if you want hard‑lifetime nodes, e.g. "720h"
