apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: x86-spot
spec:
  weight: 10
  limits:
    cpu: "32"
  template:
    spec:
      nodeClassRef:
        name: ec2-nodeclass-default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: "24h"

