apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: ec2-nodeclass-default
spec:
  role: KarpenterNodeRole-opsfleet-eks-dev-us-east-1   # <- instance profile!
  amiFamily: AL2023

  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery/opsfleet-eks-dev-us-east-1: "owned"

  securityGroupSelectorTerms:
  - tags:
      aws:eks:cluster-name: opsfleet-eks-dev-us-east-1

  tags:
    owner: daniel
    project: opsfleet-test
