apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: arm64-spot
spec:
  template:
    metadata:
      labels:
        kubernetes.io/arch: arm64
        capacity: spot
    spec:
      nodeClassRef:
        name: ec2-nodeclass-default
      requirements:
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["spot","on-demand"]
  limits:
    cpu: "32"          # test‑env quota, ~8 small nodes
  weight: 10
  disruption:
    consolidationPolicy: WhenUnderutilized