# ------------------------------
# ARM64 Spot NodePool
# ------------------------------
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: arm64-spot
spec:
  limits:
    cpu: "256"                      # soft quota: ~8 × t4g.medium etc.
  weight: 10
  template:
    metadata:
      labels:
        kubernetes.io/arch: arm64
        capacity: spot
    spec:
      nodeClassRef:
        name: ec2-nodeclass-default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]  # allow fallback
  disruption:
    consolidationPolicy: WhenUnderutilized
