apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: x86-spot
spec:
  template:
    metadata:
      labels:
        kubernetes.io/arch: amd64
        capacity: spot
    spec:
      nodeClassRef:
        name: ec2-nodeclass-default
      requirements:
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["spot","on-demand"]
  limits:
    cpu: "32"
  weight: 5
  disruption:
    consolidationPolicy: WhenUnderutilized