# karpenter-provisioners/provisioner-x86-spot.yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: x86-spot
spec:
  limits:
    cpu: "32"
  weight: 10
  template:
    metadata:
      labels:
        kubernetes.io/arch: amd64
        capacity: spot
    spec:
      nodeClassRef:
        name: ec2-nodeclass-default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.small", "t3.medium", "c6i.medium", "m6i.medium"]

  disruption:
    consolidationPolicy: WhenUnderutilized
