name: Deploy Karpenter provisioners
on:
  push:
    paths:
      - "karpenter-provisioners/**.yaml"
      - ".github/workflows/deploy-karpenter-provisioners.yml"
    branches: [ main ]
  workflow_dispatch: {}           # manual run

jobs:
  apply:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # required for OIDC
      contents: read

    steps:
    # 1.  Checkout code
    - uses: actions/checkout@v4

    # 2.  Assume the short‑lived AWS role via OIDC
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region:     ${{ secrets.AWS_REGION }}

    # 3.  Install kubectl (lightweight)
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: "latest"

    # 4.  Update kubeconfig (no file saved – token only)
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --name ${{ secrets.CLUSTER_NAME }} \
          --region ${{ secrets.AWS_REGION }} \
          --role-arn ${{ secrets.AWS_ROLE_ARN }}

    # 5a.  Validate manifests (optional but recommended)
    - name: Kubeval
      uses: instrumenta/kubeval-action@v0.2.0
      with:
        files: karpenter-provisioners

    # 5b.  Apply manifests
    - name: Apply provisioners
      run: |
        # NodeClass first, then Provisioners (they reference the class)
        kubectl apply -f karpenter-provisioners/nodeclass.yaml
        kubectl apply -f karpenter-provisioners/provisioner-arm64-spot.yaml
        kubectl apply -f karpenter-provisioners/provisioner-x86-spot.yaml

    # 6.  Diff output in PRs (optional)
    - name: Show changes (kubectl diff)
      if: github.event_name == 'pull_request'
      run: kubectl diff -f karpenter-provisioners || true
